# Generated by Django 5.0.4 on 2025-06-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_app", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="main_banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("added_at", models.DateField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("start", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product_app.product_color_image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sub_banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("added_at", models.DateField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("start", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product_app.product_color_image",
                    ),
                ),
            ],
        ),
    ]
