# Generated by Django 5.0.4 on 2025-06-14 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("product_app", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "serial_number",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("payment_method", models.CharField(max_length=20)),
                (
                    "payment_online_id",
                    models.CharField(
                        blank=True, default="0000", max_length=50, null=True
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("coupon_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "coupon_discount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_to_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.user_address",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("size", models.CharField(default="toadd", max_length=20)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "final_product_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Order Pending", "Order Pending"),
                            ("Order confirmed", "Order confirmed"),
                            ("Shipped", "Shipped"),
                            ("Out For Delivery", "Out For Delivery"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Returned", "Returned"),
                        ],
                        default="Order Pending",
                        max_length=30,
                    ),
                ),
                ("cancel_return_confirm", models.BooleanField(default=False)),
                ("accept_order", models.BooleanField(default=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_all",
                        to="order_app.order",
                    ),
                ),
                (
                    "product_added",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product_app.product_color_image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cancelled_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("request_date", models.DateField(auto_now_add=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                (
                    "has_dispatched",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordered_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_app.order_items",
                    ),
                ),
            ],
        ),
    ]
